services:
  - type: web
    name: extrator-tabelas-pdf
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app_ui.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18